name: Deploy SAM App

on:
  push:
    branches:
      - main
      - dev

env:
  AWS_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'production' || 'dev' }}
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install AWS SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Build SAM App
        run: sam build

      - name: Deploy SAM App
        run: |
          sam deploy \
            --config-env ${{ github.ref_name == 'main' && 'production' || 'dev' }} \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset
